# 1.0 Tokenization

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
tf.strings.unicode_decode("সকল", input_encoding='UTF-8') 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2488, 2453, 2482], dtype=int32)>

In [12]:
tf.strings.unicode_decode('আমি ভালবাসি বই পড়তে', 'UTF-8')

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([2438, 2478, 2495,   32, 2477, 2494, 2482, 2476, 2494, 2488, 2495,
         32, 2476, 2439,   32, 2474, 2524, 2468, 2503], dtype=int32)>

In [50]:
sentences = ['আমি ভালবাসি বই পড়তে।', 'আমি ভালবাসি বই লিখতে ! ।']

tokenizer = Tokenizer(num_words = 10, filters='!।')
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
print(word_index, end='\n\n')

word_counts = tokenizer.word_counts
print(word_counts)

{'আমি': 1, 'ভালবাসি': 2, 'বই': 3, 'পড়তে': 4, 'লিখতে': 5}

OrderedDict({'আমি': 2, 'ভালবাসি': 2, 'বই': 2, 'পড়তে': 1, 'লিখতে': 1})


In [54]:
tokenizer.get_config()

{'num_words': 10,
 'filters': '!।',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 2,
 'word_counts': '{"\\u0986\\u09ae\\u09bf": 2, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 2, "\\u09ac\\u0987": 2, "\\u09aa\\u09dc\\u09a4\\u09c7": 1, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 1}',
 'word_docs': '{"\\u09ac\\u0987": 2, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 2, "\\u09aa\\u09dc\\u09a4\\u09c7": 1, "\\u0986\\u09ae\\u09bf": 2, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 1}',
 'index_docs': '{"3": 2, "2": 2, "4": 1, "1": 2, "5": 1}',
 'index_word': '{"1": "\\u0986\\u09ae\\u09bf", "2": "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf", "3": "\\u09ac\\u0987", "4": "\\u09aa\\u09dc\\u09a4\\u09c7", "5": "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7"}',
 'word_index': '{"\\u0986\\u09ae\\u09bf": 1, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 2, "\\u09ac\\u0987": 3, "\\u09aa\\u09dc\\u09a4\\u09c7": 4, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 5